---
inject: true
to: .infra/helm/prod/config.yaml
append: true
skip_if: NEXT_PUBLIC_SERVICE_<%=h.changeCase.upperCase(serviceName)%>_API
---
NEXT_PUBLIC_SERVICE_<%=h.changeCase.upperCase(serviceName)%>_API='https://geni.kitabisa.com/<%=serviceName%>'
