---
inject: true
to: .local/helm/local/config.yaml
append: true
skip_if: NEXT_PUBLIC_SERVICE_<%=h.changeCase.upperCase(serviceName)%>_API
---
      NEXT_PUBLIC_SERVICE_<%=h.changeCase.upperCase(serviceName)%>_API='https://geni.kitabisa.xyz/<%=serviceName%>'